### ISSUE TITLE
Pretrained model & paper

### ISSUE THREAD

**Issue by ghost** [denabazazian/scene_text_segmentation#1]
@denabazazian hi,
upload a pretrained model so that we can test the performance.
also where is the paper for this repo?

**Comment by denabazazian** [comment]
Thanks for your interest in our work. The pretrained model is around 1GB and that's the reason that we couldn't add it in this repository. If you follow all the steps of training process, then you can achieve the trained model of this pipeline. Also, the paper has been accepted in an ICCV workshop and will be out in the few weeks.

**Comment by deepseek** [comment]
@denabazazian You can upload the model to Google Drive.
I prefer testing the model first.

**Comment by ghost** [comment]
@denabazazian Then, add some results showing the detected textlines.

**Comment by denabazazian** [comment]
You can see some qualitative results of our model in README.  The model works for pixel-wise text segmentation and it is for removing the background pixels of scene images and just keeping the text pixels, it is different with the pipelines for detecting text lines.

**Comment by ghost** [comment]
So it doesn't actually detect the textlines? it only creates a binarized image of the detected text?

hmmmm.....
 you are almost there.

You can use it to make a textline detector

**Comment by denabazazian** [comment]
We have another work for text line detection. You can find the [Paper](https://arxiv.org/pdf/1809.00854v2.pdf) and [Repository](https://github.com/denabazazian/SoftPHOC_TextDescriptor) of that project. We also have both version of Pytorch and Tensorflow code for that.
